### ISSUE TITLE
Create 1.3.1 plugin release

### ISSUE THREAD

**Issue by odinsbane** [Living-Technologies/DM3D#15]
This is for organizing issues required to fix before creating the 1.3.1 plugin release.
```[tasklist]
### Tasks
- [ ] https://github.com/Living-Technologies/DM3D/issues/7
- [ ] https://github.com/Living-Technologies/DM3D/issues/16
- [ ] https://github.com/Living-Technologies/DM3D/issues/18
```
